baseurl: "/"
title: Daniel Heitmann
theme: PaperMod
languagecode: en
defaultcontentlanguage: en
paginate: 15
canonifyurls: true
pygmentsstyle: b2
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
permalinks:
  posts: "/posts/:title/"
params:
  author: Daniel Heitmann
  profileMode:
    enabled: true
    imageUrl: images/daniel_closeup.jpg
    title: I'm Daniel, hi!
    subtitle: Pragmatic Generalist | Consultant | Engineering Manager | Site Reliability Engineer

  socialIcons: # optional
  - name: "Github"
    url: "https://github.com/dictvm"
  - name: "Codeberg"
    url: "https://codeberg.org/dictvm"
  - name: "RSS"
    url: "https://dictvm.org/posts/index.xml"
    rel: "alternate"
    type: "application/rss+xml"

  subinfo:
  footercontent: ""
  dateformat: "January 2, 2006"
  hideCredits: false
  hideCopyright: false
  defaultTheme: auto
  ShowReadingTime: true
  maxSeeAlsoItems: 5
  custom_css: []
  custom_js: []

menu:
  main:
  - name: About
    weight: 1
    url: about
  - name: Blog
    weight: 2
    url: posts
  - name: Projects
    weight: 3
    url: projects
  - name: Contact
    weight: 4
    url: contact
