baseurl = "https://www.dictvm.org/"
title = "Daniel Heitmann"

theme = "hugo-coder"
colorscheme = "auto"

googleAnalytics = "UA-56464004-1"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 10
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[permalinks]
posts = "/posts/:title/"

[params]
    author = "Daniel Heitmann | dictvm"
    description = "Thoughts of a systems engineer with his head up in the cloud"
    keywords = "blog,developer,sre,sitereliabilityengineering,duesseldorf,personal,devops,sre,cloudcomputing,kubernetes"
    info = "Cloud, coffee, bicycles, veganism, antifascism."
    subinfo = "Site Reliability Engineering, Consulting, Systems Architecture, Cloud-native Software, Cycling, Urban Development, Black Metal"
    avatarurl = "images/daniel.jpg"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/dictvm"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/dictvm"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/danielheitmannsre"
[[params.social]]
    name = "Medium"
    icon = "fa fa-medium fa-2x"
    weight = 5
    url = "https://medium.com/@dictvm"
[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram fa-2x"
    weight = 6
    url = "https://instagram.com/dictvm"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss fa-2x"
    weight = 6
    url = "https://dictvm.org/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "projects/"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "contact/"