baseurl: "/"
title: Daniel Heitmann
theme: PaperMod
languagecode: en
defaultcontentlanguage: en
paginate: 15
canonifyurls: true
pygmentsstyle: b2
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
permalinks:
  posts: "/posts/:title/"
params:
  author: Daniel's blog
  profileMode:
    enabled: true
    imageUrl: images/daniel_closeup.jpg
    title: This was Daniel's blog
    subtitle: It's read-only and is unlikely to receive updates anymore.

  subinfo:
  footercontent: ""
  dateformat: "January 2, 2006"
  hideCredits: true
  hideCopyright: true
  defaultTheme: auto
  ShowReadingTime: true
  maxSeeAlsoItems: 5
  custom_css: []
  custom_js: []

menu:
  main:
  - name: Contact
    weight: 0
    url: contact
