baseurl: "/"
title: Daniel Heitmann | dictvm
theme: PaperMod
languagecode: en
defaultcontentlanguage: en
paginate: 15
canonifyurls: true
pygmentsstyle: b2
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
permalinks:
  posts: "/posts/:title/"
params:
  author: Daniel Heitmann | dictvm
  profileMode:
    enabled: true
    imageUrl: images/daniel.jpg
    title: Hi and welcome!
    subtitle: "Cloud Engineering, Antifascism, Politics, Cycling, Kung Fu & Black Metal."

  socialIcons: # optional
    - name: "RSS"
      url: "https://dictvm.org/posts/index.xml"
      rel: "alternate"
      type: "application/rss+xml"
    - name: "Github"
      url: "https://github.com/dictvm"
    - name: "Codeberg"
      url: "https://codeberg.org/dictvm"      
    - name: "Mastodon"
      url: "https://chaos.social/web/accounts/319120"
    - name: "Medium"
      url: "https://medium.com/@dictvm"

  subinfo: >-
    Site Reliability Engineering, Consulting, Systems Architecture, Cloud-native
    Software, Cycling, Urban Development, Black Metal

  footercontent: ""
  dateformat: "January 2, 2006"
  hideCredits: false
  hideCopyright: false
  defaultTheme: auto
  ShowReadingTime: true
  maxSeeAlsoItems: 5
  custom_css: []
  custom_js: []

menu:
  main:
    - name: About
      weight: 1
      url: about/
    - name: Posts
      weight: 2
      url: posts/
    - name: Projects
      weight: 3
      url: projects/
    - name: Reach out
      weight: 4
      url: contact/
