baseurl: "/"
title: Daniel Heitmann | dictvm
theme: PaperMod
googleAnalytics: UA-56464004-1
languagecode: en
defaultcontentlanguage: en
paginate: 15
canonifyurls: true
pygmentsstyle: b2
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
permalinks:
  posts: "/posts/:title/"
params:
  author: Daniel Heitmann | dictvm
  profileMode:
    enabled: true
    imageUrl: images/daniel.jpg
    title: Hi and welcome!
    subtitle: I'm Daniel, writing about topics ranging from Cloud Infrastructure, Site Reliability Engineering, bicycles, Black Metal, politics and whatever rabbit hole I'm following at the time.

  socialIcons: # optional
    - name: "RSS"
      url: "https://dictvm.org/posts/index.xml"
      rel: alternate
      type: application/rss+xml
    - name: "Github"
      url: "https://github.com/dictvm"
    - name: "Twitter"
      url: "https://twitter.com/dictvm"
    - name: "Instagram"
      url: "https://instagram.com/dictvm"
    - name: "Ko-Fi"
      url: "https://ko-fi.com/dictvm"
    - name: "Medium"
      url: "https://medium.com/@dictvm"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/danielheitmannsre"

  keywords: >-
    blog,developer,sre,sitereliabilityengineering,duesseldorf,personal,devops,sre,cloudcomputing,kubernetes,blackmetal
  info: "Cloud, Coffee, Cycling, Veganism, Antifascism & Black Metal."
  subinfo: >-
    Site Reliability Engineering, Consulting, Systems Architecture, Cloud-native
    Software, Cycling, Urban Development, Black Metal

  footercontent: ""
  dateformat: "January 2, 2006"
  hideCredits: false
  hideCopyright: false
  defaultTheme: auto
  ShowReadingTime: true
  maxSeeAlsoItems: 5
  custom_css: []
  custom_js: []

menu:
  main:
    - name: About
      weight: 1
      url: about/
    - name: Blog
      weight: 2
      url: posts/
    - name: Projects
      weight: 3
      url: projects/
    - name: Buy me a ☕
      weight: 4
      url: https://ko-fi.com/dictvm
      rel: alternate
    - name: Reach out
      weight: 5
      url: contact/
