baseurl: "/"
title: Daniel's blog
theme: PaperMod
languagecode: en
defaultcontentlanguage: en
paginate: 15
canonifyurls: true
pygmentsstyle: b2
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
params:
  author: Daniel's blog
  profileMode:
    enabled: true
    imageUrl: images/daniel_closeup.jpg
    title: This was Daniel's blog
    subtitle: It's read-only and is unlikely to receive updates anymore.
  socialIcons: # optional
  - name: "RSS"
    url: "https://dictvm.org/posts/index.xml"
    rel: "alternate"
    type: "application/rss+xml"
  subinfo:
  footercontent: ""
  dateformat: "January 2, 2006"
  hideCredits: true
  hideCopyright: true
  defaultTheme: auto
  ShowReadingTime: true
  maxSeeAlsoItems: 5
  custom_css: []
  custom_js: []

menu:
  main:
  - name: Contact
    weight: 0
    url: contact
  - name: Posts
    weight: 1
    url: posts
